#import <Foundation/Foundation.h>

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_PACKAGE;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_METAPACKAGE;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_ARCHIVE;

extern NSString * const PB_BUILDNOTIFICATION_SPLITTING_FORKS;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_BOM;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_BOM;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_PAX;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_PAX;

extern NSString * const PB_BUILDNOTIFICATION_CLEANING;

extern NSString * const PB_BUILDNOTIFICATION_PREPARING_BUILD_FOLDER;

extern NSString * const PB_BUILDNOTIFICATION_CREATING_INFOPLIST;

extern NSString * const PB_BUILDNOTIFICATION_CREATING_DESCRIPTIONPLIST;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_BACKGROUNDIMAGE;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_WELCOMEMESSAGE;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_READMEMESSAGE;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_LICENSEDOCUMENTS;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_REQUIREMENTS;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_SCRIPTS;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_PLUGINS;

extern NSString * const PB_BUILDNOTIFICATION_COPYING_ADDITIONALRESOURCES;

extern NSString * const PB_BUILDNOTIFICATION_CREATING_PACKAGEVERSION;

extern NSString * const PB_BUILDNOTIFICATION_CREATING_TOKENDEFINITIONSPLIST;


extern NSString * const PB_BUILDNOTIFICATION_UNKNOWNERROR;

extern NSString * const PB_BUILDNOTIFICATION_CANT_CREATEFOLDER;

extern NSString * const PB_BUILDNOTIFICATION_CANT_CREATEFILE;

extern NSString * const PB_BUILDNOTIFICATION_CANT_COPYFILE;

extern NSString * const PB_BUILDNOTIFICATION_CANT_REMOVEFILE;

extern NSString * const PB_BUILDNOTIFICATION_OUT_OF_MEMORY;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_PAX_FAILED;

extern NSString * const PB_BUILDNOTIFICATION_BUILDING_BOM_FAILED;

extern NSString * const PB_BUILDNOTIFICATION_CLEANING_FAILED;

extern NSString * const PB_BUILDNOTIFICATION_MISSING_INFORMATION;

extern NSString * const PB_BUILDNOTIFICATION_MISSING_FILE;

extern NSString * const PB_BUILDNOTIFICATION_MISSING_SCRATCH_FOLDER;

extern NSString * const PB_BUILDNOTIFICATION_FOLDER_DOES_NOT_EXIST;

extern NSString * const PB_BUILDNOTIFICATION_INSUFFICIENT_PRIVILEGES;

extern NSString * const PB_BUILDNOTIFICATION_SET_INSUFFICIENT_PRIVILEGES;

extern NSString * const PB_BUILDNOTIFICATION_INCORRECT_FILE_TYPE;

extern NSString * const PB_BUILDNOTIFICATION_TWIN_COMPONENTS;

extern NSString * const PB_BUILDNOTIFICATION_SPLITFORKS_MISSINGTOOL;

extern NSString * const PB_BUILDNOTIFICATION_SPLITFORKS_NONHFSVOLUME;

extern NSString * const PB_BUILDNOTIFICATION_SPLITFORKS_ERROR;

extern NSString * const PB_BUILDNOTIFICATION_BUILDCANCELLED_UNSAVEDFILE;