#import <Foundation/Foundation.h>

extern NSString * const PBPREFERENCEPANE_FILES_NOTIFICATION_DEFAULTS_DIDCHANGE;

extern NSString * const PBPREFERENCEPANE_FILES_DEFAULPERMISSIONSMODE;
extern NSString * const PBPREFERENCEPANE_FILES_DEFAULTREFERENCESTYLE;

extern NSString * const PBPREFERENCEPANE_FILES_SHOWCUSTOMIZATIONDIALOG;


extern NSString * const PBPREFERENCEPANE_FILES_SPLITFORKSTOOLNAME;

extern NSString * SPLITFORKSTOOL_GOLDIN;
extern NSString * SPLITFORKSTOOL_SPLITFORKS;

#define SPLITFORKSTOOL_GOLDIN_ID		0
#define SPLITFORKSTOOL_SPLITFORKS_ID	1