#import <Foundation/Foundation.h>

extern NSString * const PBPREFERENCEPANE_IMPORT_NOTIFICATION_DEFAULTS_DIDCHANGE;

extern NSString * const PBPREFERENCEPANE_IMPORT_COPY_COMPONENT;
extern NSString * const PBPREFERENCEPANE_IMPORT_SUBCOMPONENTS;

extern NSString * const PBPREFERENCEPANE_IMPORT_DEFAULTREFERENCESTYLE;