#import "PBPreferencePaneFilesController+Constants.h"

NSString * const PBPREFERENCEPANE_FILES_NOTIFICATION_DEFAULTS_DIDCHANGE=@"filesDefaultsDidChange";

NSString * const PBPREFERENCEPANE_FILES_DEFAULPERMISSIONSMODE=@"Default Permissions Mode";

NSString * const PBPREFERENCEPANE_FILES_DEFAULTREFERENCESTYLE=@"Default Reference Style";

NSString * const PBPREFERENCEPANE_FILES_SHOWCUSTOMIZATIONDIALOG=@"Show Customization Dialog";

NSString * const PBPREFERENCEPANE_FILES_SPLITFORKSTOOLNAME=@"SplitForks Tool Name";

NSString * SPLITFORKSTOOL_GOLDIN=@"goldin";
NSString * SPLITFORKSTOOL_SPLITFORKS=@"SplitForks";